namespace ModAdvancedGameChanges.Constants
{
    public static class Tweakables
    {
        public static class Mod
        {
            public const string AGC_TWEAKABLE_SKILL_LEVELS = "AGC_TWEAKABLE_SKILL_LEVELS";

            public const string AGC_TWEAKABLE_SKILL_POINTS_FORMAT = "AGC_TWEAKABLE_SKILL_POINTS_{0}";


            public const string AGC_TWEAKABLE_DOCTOR_LEVEL_POINTS_FORMAT = "AGC_TWEAKABLE_DOCTOR_LEVEL_POINTS_{0}";

            public const string AGC_TWEAKABLE_NURSE_LEVEL_POINTS_FORMAT = "AGC_TWEAKABLE_NURSE_LEVEL_POINTS_{0}";

            public const string AGC_TWEAKABLE_LAB_SPECIALIST_LEVEL_POINTS_FORMAT = "AGC_TWEAKABLE_LAB_SPECIALIST_LEVEL_POINTS_{0}";

            public const string AGC_TWEAKABLE_JANITOR_LEVEL_POINTS_FORMAT = "AGC_TWEAKABLE_JANITOR_LEVEL_POINTS_{0}";


            public const string AGC_TWEAKABLE_ENABLE_EXTRA_LEVELING_PERCENT = "AGC_TWEAKABLE_ENABLE_EXTRA_LEVELING_PERCENT";

            public const string AGC_TWEAKABLE_ALLOWED_CLINIC_DOCTORS_LEVEL = "AGC_TWEAKABLE_ALLOWED_CLINIC_DOCTORS_LEVEL";

            public const string AGC_TWEAKABLE_TRAINING_HOUR_POINTS = "AGC_TWEAKABLE_TRAINING_HOUR_POINTS";

            public const string AGC_TWEAKABLE_CLEANING_TIME_DIRT = "AGC_TWEAKABLE_CLEANING_TIME_DIRT";
            public const string AGC_TWEAKABLE_CLEANING_TIME_BLOOD = "AGC_TWEAKABLE_CLEANING_TIME_BLOOD";
        }

        public static class Vanilla
        {
            public const string LEVELING_RATE_PERCENT = "LEVELING_RATE_PERCENT";

            public const string DLC_ADMIN_PATHOLOGY_ENABLED = "DLC_ADMIN_PATHOLOGY_ENABLED";

            public const string TWEAKABLE_MAIN_SKILL_POINTS = "TWEAKABLE_MAIN_SKILL_POINTS";
            public const string TWEAKABLE_JANITOR_DEXTERITY_SKILL_POINTS = "TWEAKABLE_JANITOR_DEXTERITY_SKILL_POINTS";
            public const string TWEAKABLE_JANITOR_MANAGER_CLEANING_BONUS_PERCENT = "TWEAKABLE_JANITOR_MANAGER_CLEANING_BONUS_PERCENT";

            public const string TWEAKABLE_PATIENT_LEAVE_TIME_HOURS = "TWEAKABLE_PATIENT_LEAVE_TIME_HOURS";
            public const string TWEAKABLE_PATIENT_LEAVE_WARNING_HOURS = "TWEAKABLE_PATIENT_LEAVE_WARNING_HOURS";
        }
    }
}