namespace ModAdvancedGameChanges.Constants
{
    public static class Tweakables
    {
        public static class Mod
        {
            public const string AGC_TWEAKABLE_AMBIGUOUS_LEAVE_MINUTES = "AGC_TWEAKABLE_AMBIGUOUS_LEAVE_MINUTES";
            public const string AGC_TWEAKABLE_ALLOWED_CLINIC_DOCTORS_LEVEL = "AGC_TWEAKABLE_ALLOWED_CLINIC_DOCTORS_LEVEL";

            public const string AGC_TWEAKABLE_COMPLICATED_DECISION_MINUTES = "AGC_TWEAKABLE_COMPLICATED_DECISION_MINUTES";

            public const string AGC_TWEAKABLE_DOCTOR_LEVEL_POINTS_FORMAT = "AGC_TWEAKABLE_DOCTOR_LEVEL_POINTS_{0}";

            public const string AGC_TWEAKABLE_DOCTOR_FILLING_REPORT_MINUTES = "AGC_TWEAKABLE_DOCTOR_FILLING_REPORT_MINUTES";
            public const string AGC_TWEAKABLE_DOCTOR_FILLING_REPORT_SKILL_POINTS = "AGC_TWEAKABLE_DOCTOR_FILLING_REPORT_SKILL_POINTS";

            public const string AGC_TWEAKABLE_EFFICIENCY_MINIMUM = "AGC_TWEAKABLE_EFFICIENCY_MINIMUM";

            public const string AGC_TWEAKABLE_EFFICIENCY_GOOD_BOSS_MINIMUM = "AGC_TWEAKABLE_EFFICIENCY_GOOD_BOSS_MINIMUM";
            public const string AGC_TWEAKABLE_EFFICIENCY_GOOD_BOSS_MAXIMUM = "AGC_TWEAKABLE_EFFICIENCY_GOOD_BOSS_MAXIMUM";

            public const string AGC_TWEAKABLE_EFFICIENCY_SATISFACTION_MINIMUM = "AGC_TWEAKABLE_EFFICIENCY_SATISFACTION_MINIMUM";
            public const string AGC_TWEAKABLE_EFFICIENCY_SATISFACTION_MAXIMUM = "AGC_TWEAKABLE_EFFICIENCY_SATISFACTION_MAXIMUM";

            public const string AGC_TWEAKABLE_EFFICIENCY_SHIFT_PREFERENCE_MINIMUM = "AGC_TWEAKABLE_EFFICIENCY_SHIFT_PREFERENCE_MINIMUM";
            public const string AGC_TWEAKABLE_EFFICIENCY_SHIFT_PREFERENCE_MAXIMUM = "AGC_TWEAKABLE_EFFICIENCY_SHIFT_PREFERENCE_MAXIMUM";

            public const string AGC_TWEAKABLE_ENABLE_EXTRA_LEVELING_PERCENT = "AGC_TWEAKABLE_ENABLE_EXTRA_LEVELING_PERCENT";

            public const string AGC_TWEAKABLE_FULFILL_NEEDS_THRESHOLD = "AGC_TWEAKABLE_FULFILL_NEEDS_THRESHOLD";
            public const string AGC_TWEAKABLE_FULFILL_NEEDS_THRESHOLD_CRITICAL = "AGC_TWEAKABLE_FULFILL_NEEDS_THRESHOLD_CRITICAL";
            public const string AGC_TWEAKABLE_FULFILL_NEEDS_REDUCTION_MINIMUM = "AGC_TWEAKABLE_FULFILL_NEEDS_REDUCTION_MINIMUM";
            public const string AGC_TWEAKABLE_FULFILL_NEEDS_REDUCTION_MAXIMUM = "AGC_TWEAKABLE_FULFILL_NEEDS_REDUCTION_MAXIMUM";

            public const string AGC_TWEAKABLE_JANITOR_CLEANING_TIME_BLOOD = "AGC_TWEAKABLE_JANITOR_CLEANING_TIME_BLOOD";
            public const string AGC_TWEAKABLE_JANITOR_CLEANING_TIME_DIRT = "AGC_TWEAKABLE_JANITOR_CLEANING_TIME_DIRT";

            public const string AGC_TWEAKABLE_JANITOR_LEVEL_POINTS_FORMAT = "AGC_TWEAKABLE_JANITOR_LEVEL_POINTS_{0}";

            public const string AGC_TWEAKABLE_LAB_SPECIALIST_LEVEL_POINTS_FORMAT = "AGC_TWEAKABLE_LAB_SPECIALIST_LEVEL_POINTS_{0}";

            public const string AGC_TWEAKABLE_NEED_BLADDER = "AGC_TWEAKABLE_NEED_BLADDER";

            public const string AGC_TWEAKABLE_NEED_BOREDOM_USING_OBJECT = "AGC_TWEAKABLE_NEED_BOREDOM_USING_OBJECT";
            public const string AGC_TWEAKABLE_NEED_BOREDOM_USING_PHONE = "AGC_TWEAKABLE_NEED_BOREDOM_USING_PHONE";
            public const string AGC_TWEAKABLE_NEED_BOREDOM_YAWNING = "AGC_TWEAKABLE_NEED_BOREDOM_YAWNING";

            public const string AGC_TWEAKABLE_NEED_HUNGER = "AGC_TWEAKABLE_NEED_HUNGER";
            public const string AGC_TWEAKABLE_NEED_HUNGER_LUNCH = "AGC_TWEAKABLE_NEED_HUNGER_LUNCH";
            public const string AGC_TWEAKABLE_NEED_HUNGER_LUNCH_EATING_TIME_MINUTES = "AGC_TWEAKABLE_NEED_HUNGER_LUNCH_EATING_TIME_MINUTES";
            public const string AGC_TWEAKABLE_NEED_HUNGER_LUNCH_COFFEE_TIME_MINUTES = "AGC_TWEAKABLE_NEED_HUNGER_LUNCH_COFFEE_TIME_MINUTES";
            public const string AGC_TWEAKABLE_NEED_HUNGER_LUNCH_PAYMENT_MEAL_MINIMUM = "AGC_TWEAKABLE_NEED_HUNGER_LUNCH_PAYMENT_MEAL_MINIMUM";
            public const string AGC_TWEAKABLE_NEED_HUNGER_LUNCH_PAYMENT_MEAL_MAXIMUM = "AGC_TWEAKABLE_NEED_HUNGER_LUNCH_PAYMENT_MEAL_MAXIMUM";
            public const string AGC_TWEAKABLE_NEED_HUNGER_LUNCH_PAYMENT_SNACK_MINIMUM = "AGC_TWEAKABLE_NEED_HUNGER_LUNCH_PAYMENT_SNACK_MINIMUM";
            public const string AGC_TWEAKABLE_NEED_HUNGER_LUNCH_PAYMENT_SNACK_MAXIMUM = "AGC_TWEAKABLE_NEED_HUNGER_LUNCH_PAYMENT_SNACK_MAXIMUM";
            public const string AGC_TWEAKABLE_NEED_HUNGER_LUNCH_PAYMENT_JUICE_MINIMUM = "AGC_TWEAKABLE_NEED_HUNGER_LUNCH_PAYMENT_JUICE_MINIMUM";
            public const string AGC_TWEAKABLE_NEED_HUNGER_LUNCH_PAYMENT_JUICE_MAXIMUM = "AGC_TWEAKABLE_NEED_HUNGER_LUNCH_PAYMENT_JUICE_MAXIMUM";
            public const string AGC_TWEAKABLE_NEED_HUNGER_LUNCH_PAYMENT_COFFEE_MINIMUM = "AGC_TWEAKABLE_NEED_HUNGER_LUNCH_PAYMENT_COFFEE_MINIMUM";
            public const string AGC_TWEAKABLE_NEED_HUNGER_LUNCH_PAYMENT_COFFEE_MAXIMUM = "AGC_TWEAKABLE_NEED_HUNGER_LUNCH_PAYMENT_COFFEE_MAXIMUM";

            public const string AGC_TWEAKABLE_NEED_REST_MINUTES = "AGC_TWEAKABLE_NEED_REST_MINUTES";
            public const string AGC_TWEAKABLE_NEED_REST_PLAY_GAME = "AGC_TWEAKABLE_NEED_REST_PLAY_GAME";
            public const string AGC_TWEAKABLE_NEED_REST_SIT = "AGC_TWEAKABLE_NEED_REST_SIT";
            public const string AGC_TWEAKABLE_NEED_REST_STUDY = "AGC_TWEAKABLE_NEED_REST_STUDY";

            public const string AGC_TWEAKABLE_NURSE_LEVEL_POINTS_FORMAT = "AGC_TWEAKABLE_NURSE_LEVEL_POINTS_{0}";

            public const string AGC_TWEAKABLE_NURSE_RECEPTION_QUESTION_MINUTES = "AGC_TWEAKABLE_NURSE_RECEPTION_QUESTION_MINUTES";
            public const string AGC_TWEAKABLE_NURSE_RECEPTION_DECISION_MINUTES = "AGC_TWEAKABLE_NURSE_RECEPTION_DECISION_MINUTES";
            public const string AGC_TWEAKABLE_NURSE_RECEPTION_QUESTION_SKILL_POINTS = "AGC_TWEAKABLE_NURSE_RECEPTION_QUESTION_SKILL_POINTS";
            public const string AGC_TWEAKABLE_NURSE_RECEPTION_NEXT_QUESTION_SKILL_POINTS = "AGC_TWEAKABLE_NURSE_RECEPTION_NEXT_QUESTION_SKILL_POINTS";

            public const string AGC_TWEAKABLE_PATIENT_MAX_WAIT_TIME_HOURS_HIGH_PRIORITY_MULTIPLIER = "AGC_TWEAKABLE_PATIENT_MAX_WAIT_TIME_HOURS_HIGH_PRIORITY_MULTIPLIER";
            public const string AGC_TWEAKABLE_PATIENT_MAX_WAIT_TIME_HOURS_MEDIUM_PRIORITY_MULTIPLIER = "AGC_TWEAKABLE_PATIENT_MAX_WAIT_TIME_HOURS_MEDIUM_PRIORITY_MULTIPLIER";
            public const string AGC_TWEAKABLE_PATIENT_MAX_WAIT_TIME_HOURS_LOW_PRIORITY_MULTIPLIER = "AGC_TWEAKABLE_PATIENT_MAX_WAIT_TIME_HOURS_LOW_PRIORITY_MULTIPLIER";

            public const string AGC_TWEAKABLE_PEDESTRIAN_MAX_COUNT = "AGC_TWEAKABLE_PEDESTRIAN_MAX_COUNT";

            public const string AGC_TWEAKABLE_SKILL_LEVELS = "AGC_TWEAKABLE_SKILL_LEVELS";

            public const string AGC_TWEAKABLE_SKILL_POINTS_FORMAT = "AGC_TWEAKABLE_SKILL_POINTS_{0}";

            public const string AGC_TWEAKABLE_SKILL_TIME_REDUCTION_MINIMUM = "AGC_TWEAKABLE_SKILL_TIME_REDUCTION_MINIMUM";
            public const string AGC_TWEAKABLE_SKILL_TIME_REDUCTION_MAXIMUM = "AGC_TWEAKABLE_SKILL_TIME_REDUCTION_MAXIMUM";

            public const string AGC_TWEAKABLE_TRAINING_HOUR_SKILL_POINTS = "AGC_TWEAKABLE_TRAINING_HOUR_SKILL_POINTS";

            public const string AGC_TWEAKABLE_VENDING_PAYMENT_EMPLOYEE_MINIMUM = "AGC_TWEAKABLE_VENDING_PAYMENT_EMPLOYEE_MINIMUM";
            public const string AGC_TWEAKABLE_VENDING_PAYMENT_EMPLOYEE_MAXIMUM = "AGC_TWEAKABLE_VENDING_PAYMENT_EMPLOYEE_MAXIMUM";

            public const string AGC_TWEAKABLE_VENDING_PAYMENT_PATIENT_MINIMUM = "AGC_TWEAKABLE_VENDING_PAYMENT_PATIENT_MINIMUM";
            public const string AGC_TWEAKABLE_VENDING_PAYMENT_PATIENT_MAXIMUM = "AGC_TWEAKABLE_VENDING_PAYMENT_PATIENT_MAXIMUM";
        }

        public static class Vanilla
        {
            public const string LEVELING_RATE_PERCENT = "LEVELING_RATE_PERCENT";

            public const string DLC_ADMIN_PATHOLOGY_ENABLED = "DLC_ADMIN_PATHOLOGY_ENABLED";

            public const string TWEAKABLE_CORRECT_DIAGNOSE_PERK_SKILL_POINTS = "TWEAKABLE_CORRECT_DIAGNOSE_PERK_SKILL_POINTS";
            public const string TWEAKABLE_CORRECT_DIAGNOSE_SKILL_POINTS = "TWEAKABLE_CORRECT_DIAGNOSE_SKILL_POINTS";

            public const string TWEAKABLE_INCORRECT_DIAGNOSE_PERK_SKILL_POINTS = "TWEAKABLE_INCORRECT_DIAGNOSE_PERK_SKILL_POINTS";
            public const string TWEAKABLE_INCORRECT_DIAGNOSE_SKILL_POINTS = "TWEAKABLE_INCORRECT_DIAGNOSE_SKILL_POINTS";

            public const string TWEAKABLE_JANITOR_DEXTERITY_SKILL_POINTS = "TWEAKABLE_JANITOR_DEXTERITY_SKILL_POINTS";
            public const string TWEAKABLE_JANITOR_MANAGER_CLEANING_BONUS_PERCENT = "TWEAKABLE_JANITOR_MANAGER_CLEANING_BONUS_PERCENT";

            public const string TWEAKABLE_MAIN_SKILL_POINTS = "TWEAKABLE_MAIN_SKILL_POINTS";

            public const string TWEAKABLE_PATIENT_LEAVE_TIME_HOURS = "TWEAKABLE_PATIENT_LEAVE_TIME_HOURS";
            public const string TWEAKABLE_PATIENT_LEAVE_WARNING_HOURS = "TWEAKABLE_PATIENT_LEAVE_WARNING_HOURS";
            public const string TWEAKABLE_PATIENT_MAX_WAIT_TIME_HOURS = "TWEAKABLE_PATIENT_MAX_WAIT_TIME_HOURS";

            public const string TWEAKABLE_REPEAT_ACTION_FREE_TIME_SKILL_POINTS = "TWEAKABLE_REPEAT_ACTION_FREE_TIME_SKILL_POINTS";
        }
    }
}